server:
  port: 8082
logging:
  level:
    root: DEBUG
azure:
 activedirectory:
   client-id: Enter_Your_WebAPI_Client_ID_Here
   tenant-id: Enter_Your_Tenant_ID_Here
   app-id-uri: api://Enter_Your_WebAPI_Client_ID_Here
   instance-uri: https://login.microsoftonline.com/