spring:
    main:
        web-application-type: none
    security:
        oauth2:
            client:
                provider:
                    azure:
                        token-uri: https://login.microsoftonline.com/Enter_Your_Tenant_ID_Here/oauth2/v2.0/token
                registration:
                    azure:
                        authorization-grant-type: client_credentials
                        client-authentication-method: CLIENT_SECRET_POST
                        client-id: Enter_Your_Client_ID_Here
                        client-secret: Enter_Your_Client_Secret_Here
                        scope: api://Enter_Your_WebAPI_Client_ID_Here/.default
app:
  api:
    base-address: http://localhost:8082
