name: Call Graph Sample CI

on:
  push:
    branches: [ main ]
    paths: ['2-Authorization-I/call-graph/**', '.github/workflows/**']
  pull_request:
    branches: [ main ]
    paths: ['2-Authorization-I/call-graph/**', '.github/workflows/**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./2-Authorization-I/call-graph

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ${{ env.relativePath }}
